version: '3.7'
services:
  web:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: ./tools/docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    links:
      - db
      - mail
      - redis
      - mercure
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: serverName=linkmat
  node:
    build:
      context: ./tools/docker/node
    command: npm run dev-server
    working_dir: /usr/src/app
    user: 1000:1000
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: linkmat
      MYSQL_PASSWORD: linkmat
      MYSQL_DATABASE: linkmat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: = db
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    links:
      - db
    ports:
      - 8888:8080
  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  spacechop:
    image: spacechop/spacechop:latest
    volumes:
      - ./spacechop.yml:/config.yml
      - ./public/uploads:/mnt/images/uploads
  redis:
    image: redis:5-alpine
  mercure:
    image: dunglas/mercure
    environment:
      JWT_KEY: mercure_subscriber
      PUBLISHER_JWT_KEY: mercure_publisher
      ALLOW_ANONYMOUS: 0
      CORS_ALLOWED_ORIGINS: 'http://linkmat.localhost:8000'
    ports:
      - 8001:80

volumes:
  db-data:
    driver: local
  search-data:
    driver: local
